server {
    listen 80;
    listen [::]:80;
    server_name nutrir.ca www.nutrir.ca;

    # Certbot webroot validation
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Serve static content
    location / {
        root /var/www/nutrir.ca;
        index index.html;
        try_files $uri $uri/ =404;
    }
}
