using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Nutrir.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class SeedFoodDatabase : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
INSERT INTO ""Foods"" (""Name"", ""ServingSize"", ""ServingSizeUnit"", ""CaloriesKcal"", ""ProteinG"", ""CarbsG"", ""FatG"", ""Tags"", ""Notes"", ""IsDeleted"")
VALUES
('Chicken Breast (grilled)', 150, 'g', 165, 31, 0, 3.6, ARRAY['general','high-protein','low-carb','low-fodmap','mediterranean','low-sodium']::text[], NULL, false),
('Salmon Fillet (baked)', 150, 'g', 220, 25, 0, 13, ARRAY['general','high-protein','mediterranean','anti-inflammatory','iron-rich']::text[], 'Rich in omega-3 fatty acids', false),
('Ground Beef (90% lean)', 150, 'g', 200, 26, 0, 11, ARRAY['general','high-protein','iron-rich','energy-dense']::text[], NULL, false),
('Turkey Breast (roasted)', 120, 'g', 125, 29, 0, 1, ARRAY['general','high-protein','low-calorie','low-fodmap','low-sodium']::text[], NULL, false),
('Cod Fillet (baked)', 150, 'g', 100, 23, 0, 1, ARRAY['general','high-protein','low-calorie','low-fodmap','mediterranean','low-sodium']::text[], NULL, false),
('Shrimp (cooked, peeled)', 120, 'g', 112, 24, 0.2, 1.7, ARRAY['general','high-protein','low-calorie','low-fodmap','mediterranean','low-sodium']::text[], NULL, false),
('Eggs (2 large, scrambled)', 100, 'g', 143, 12, 1, 10, ARRAY['general','high-protein','balanced','prenatal','low-fodmap']::text[], NULL, false),
('Egg Whites (3 large)', 100, 'g', 48, 11, 0.5, 0.2, ARRAY['general','high-protein','low-calorie','low-fodmap','low-sodium']::text[], NULL, false),
('Tofu (firm)', 200, 'g', 160, 17, 3, 9, ARRAY['general','high-protein','low-fodmap','anti-inflammatory','low-sodium']::text[], NULL, false),
('Tempeh', 100, 'g', 210, 20, 9, 11, ARRAY['general','high-protein','iron-rich','anti-inflammatory']::text[], NULL, false),
('Pork Tenderloin (roasted)', 120, 'g', 130, 26, 0, 3, ARRAY['general','high-protein','low-fodmap']::text[], NULL, false),
('Canned Tuna (in water)', 120, 'g', 110, 26, 0, 1, ARRAY['general','high-protein','low-calorie','low-fodmap','low-sodium','mediterranean']::text[], NULL, false),
('Lentils (cooked)', 100, 'g', 116, 9, 20, 0.4, ARRAY['general','high-protein','iron-rich','folate-rich','prenatal','low-gi','diabetic-friendly','low-sodium']::text[], NULL, false),
('Chickpeas (cooked)', 100, 'g', 164, 9, 27, 2.6, ARRAY['general','high-protein','iron-rich','folate-rich','mediterranean','low-gi']::text[], NULL, false),
('Black Beans (cooked)', 100, 'g', 132, 9, 24, 0.5, ARRAY['general','high-protein','iron-rich','folate-rich','low-gi','diabetic-friendly','low-sodium']::text[], NULL, false),
('Edamame (shelled)', 100, 'g', 122, 11, 9, 5, ARRAY['general','high-protein','folate-rich','low-gi','anti-inflammatory']::text[], NULL, false),
('Rolled Oats (dry)', 100, 'g', 389, 13, 67, 7, ARRAY['general','high-carb','energy-dense','low-gi','diabetic-friendly','low-sodium','balanced']::text[], NULL, false),
('Oatmeal (cooked)', 250, 'g', 158, 5, 27, 3, ARRAY['general','high-carb','low-gi','diabetic-friendly','balanced','low-sodium']::text[], NULL, false),
('Brown Rice (cooked)', 100, 'g', 112, 3, 23, 1, ARRAY['general','high-carb','low-gi','low-fodmap','low-sodium','mediterranean']::text[], NULL, false),
('White Rice (cooked)', 100, 'g', 130, 3, 28, 0.3, ARRAY['general','high-carb','low-fodmap','low-sodium']::text[], NULL, false),
('Quinoa (cooked)', 100, 'g', 120, 4, 21, 2, ARRAY['general','high-carb','iron-rich','folate-rich','mediterranean','low-gi','low-sodium']::text[], NULL, false),
('Whole Wheat Pasta (cooked)', 100, 'g', 131, 5, 27, 1, ARRAY['general','high-carb','energy-dense','low-gi','low-sodium']::text[], NULL, false),
('Pasta (cooked)', 100, 'g', 158, 5, 31, 1.1, ARRAY['general','high-carb','energy-dense']::text[], NULL, false),
('Whole Wheat Bread (1 slice)', 30, 'g', 70, 4, 12, 1, ARRAY['general','high-carb','low-gi','balanced']::text[], NULL, false),
('Sweet Potato (baked)', 100, 'g', 90, 2, 21, 0.1, ARRAY['general','high-carb','low-gi','prenatal','low-fodmap','low-sodium','anti-inflammatory']::text[], NULL, false),
('Potato (baked, with skin)', 100, 'g', 93, 2, 21, 0.1, ARRAY['general','high-carb','low-fodmap','low-sodium']::text[], NULL, false),
('Corn Tortilla (1 small)', 25, 'g', 55, 1.5, 11, 0.7, ARRAY['general','high-carb','low-fodmap']::text[], NULL, false),
('Couscous (cooked)', 100, 'g', 112, 4, 23, 0.2, ARRAY['general','high-carb','mediterranean','low-sodium']::text[], NULL, false),
('Greek Yogurt (plain, 2%)', 200, 'g', 146, 20, 8, 3.5, ARRAY['general','high-protein','balanced','low-gi','prenatal','low-fodmap']::text[], NULL, false),
('Cottage Cheese (2%)', 120, 'g', 97, 14, 5, 2.5, ARRAY['general','high-protein','low-gi','balanced']::text[], NULL, false),
('Whole Milk', 250, 'mL', 150, 8, 12, 8, ARRAY['general','balanced','prenatal']::text[], NULL, false),
('Skim Milk', 250, 'mL', 90, 9, 13, 0.2, ARRAY['general','high-protein','low-calorie','low-gi']::text[], NULL, false),
('Cheddar Cheese', 30, 'g', 113, 7, 0.4, 9, ARRAY['general','high-protein','energy-dense','low-fodmap']::text[], NULL, false),
('Mozzarella (part-skim)', 30, 'g', 78, 7, 1, 5, ARRAY['general','high-protein','mediterranean','low-fodmap']::text[], NULL, false),
('Parmesan Cheese (grated)', 30, 'g', 110, 10, 1, 7, ARRAY['general','high-protein','mediterranean','energy-dense','low-fodmap']::text[], NULL, false),
('Plain Yogurt (whole)', 150, 'g', 90, 5, 8, 4, ARRAY['general','balanced','prenatal','low-gi']::text[], NULL, false),
('Broccoli (steamed)', 120, 'g', 44, 3, 7, 0.4, ARRAY['general','low-calorie','folate-rich','prenatal','anti-inflammatory','low-gi','diabetic-friendly','low-sodium','low-fodmap']::text[], NULL, false),
('Spinach (raw)', 100, 'g', 32, 3, 4, 0.4, ARRAY['general','low-calorie','iron-rich','folate-rich','prenatal','anti-inflammatory','low-gi','diabetic-friendly','low-sodium']::text[], NULL, false),
('Kale (raw, chopped)', 100, 'g', 60, 4, 9, 0.9, ARRAY['general','low-calorie','iron-rich','folate-rich','prenatal','anti-inflammatory','low-gi','low-sodium']::text[], NULL, false),
('Zucchini (cooked)', 120, 'g', 20, 1.2, 3, 0.4, ARRAY['general','low-calorie','low-gi','diabetic-friendly','low-fodmap','low-sodium','mediterranean']::text[], NULL, false),
('Bell Pepper (raw)', 120, 'g', 31, 1, 6, 0.3, ARRAY['general','low-calorie','folate-rich','low-gi','diabetic-friendly','low-fodmap','low-sodium','anti-inflammatory']::text[], NULL, false),
('Carrots (raw)', 100, 'g', 45, 1, 10, 0.2, ARRAY['general','low-calorie','low-gi','prenatal','low-fodmap','low-sodium']::text[], NULL, false),
('Tomato (raw, medium)', 120, 'g', 22, 1, 4, 0.2, ARRAY['general','low-calorie','low-gi','mediterranean','anti-inflammatory','low-sodium','low-fodmap']::text[], NULL, false),
('Cucumber (raw)', 150, 'g', 20, 0.7, 4, 0.1, ARRAY['general','low-calorie','low-gi','diabetic-friendly','low-fodmap','low-sodium']::text[], NULL, false),
('Asparagus (steamed)', 100, 'g', 27, 2.5, 4, 0.2, ARRAY['general','low-calorie','folate-rich','prenatal','low-gi','low-sodium','anti-inflammatory']::text[], NULL, false),
('Cauliflower (steamed)', 120, 'g', 30, 2, 5, 0.3, ARRAY['general','low-calorie','low-gi','diabetic-friendly','low-sodium','low-fodmap']::text[], NULL, false),
('Green Beans (steamed)', 120, 'g', 38, 2, 7, 0.2, ARRAY['general','low-calorie','low-gi','low-fodmap','low-sodium']::text[], NULL, false),
('Brussels Sprouts (roasted)', 100, 'g', 52, 3, 9, 0.5, ARRAY['general','low-calorie','folate-rich','anti-inflammatory','low-gi','low-sodium']::text[], NULL, false),
('Banana (medium)', 120, 'g', 112, 1.3, 27, 0.4, ARRAY['general','high-carb','energy-dense','low-fodmap','low-sodium']::text[], NULL, false),
('Blueberries', 100, 'g', 60, 0.7, 14, 0.3, ARRAY['general','low-calorie','anti-inflammatory','low-gi','low-sodium','prenatal']::text[], NULL, false),
('Strawberries', 120, 'g', 36, 0.7, 8, 0.3, ARRAY['general','low-calorie','anti-inflammatory','low-gi','diabetic-friendly','low-sodium','low-fodmap']::text[], NULL, false),
('Mixed Berries', 120, 'g', 55, 1, 12, 0.4, ARRAY['general','low-calorie','anti-inflammatory','low-gi','low-sodium']::text[], NULL, false),
('Apple (medium, with skin)', 180, 'g', 104, 0.5, 25, 0.3, ARRAY['general','low-calorie','low-gi','low-sodium','low-fodmap']::text[], NULL, false),
('Orange (medium)', 140, 'g', 65, 1, 15, 0.2, ARRAY['general','low-calorie','folate-rich','prenatal','low-gi','low-sodium']::text[], NULL, false),
('Grapes (seedless)', 120, 'g', 75, 0.7, 18, 0.2, ARRAY['general','high-carb','low-sodium']::text[], NULL, false),
('Mango (sliced)', 165, 'g', 108, 1, 25, 0.6, ARRAY['general','high-carb','folate-rich','low-sodium']::text[], NULL, false),
('Olive Oil (extra virgin)', 15, 'mL', 124, 0, 0, 14, ARRAY['general','energy-dense','mediterranean','anti-inflammatory','low-fodmap','low-sodium']::text[], NULL, false),
('Avocado (half)', 100, 'g', 180, 2, 9, 15, ARRAY['general','energy-dense','anti-inflammatory','low-gi','mediterranean','low-sodium','low-fodmap']::text[], NULL, false),
('Almonds (raw)', 30, 'g', 170, 6, 6, 14, ARRAY['general','energy-dense','low-gi','diabetic-friendly','anti-inflammatory','low-fodmap','low-sodium']::text[], NULL, false),
('Walnuts (raw)', 30, 'g', 196, 4, 4, 18, ARRAY['general','energy-dense','anti-inflammatory','mediterranean','low-sodium','low-fodmap']::text[], NULL, false),
('Peanut Butter (natural)', 32, 'g', 190, 8, 6, 16, ARRAY['general','energy-dense','high-protein','balanced']::text[], NULL, false),
('Chia Seeds', 30, 'g', 138, 5, 12, 9, ARRAY['general','energy-dense','anti-inflammatory','iron-rich','low-gi','low-sodium']::text[], 'High in fiber and omega-3', false),
('Flaxseeds (ground)', 30, 'g', 160, 5, 8, 12, ARRAY['general','energy-dense','anti-inflammatory','iron-rich','low-gi','low-sodium']::text[], 'High in fiber and omega-3', false),
('Pumpkin Seeds (raw)', 30, 'g', 170, 9, 4, 14, ARRAY['general','energy-dense','iron-rich','low-gi','low-sodium']::text[], NULL, false),
('Cashews (raw)', 30, 'g', 170, 5, 9, 13, ARRAY['general','energy-dense','iron-rich']::text[], NULL, false),
('Tahini', 30, 'g', 160, 5, 3, 14, ARRAY['general','energy-dense','iron-rich','mediterranean','low-gi']::text[], NULL, false),
('Protein Smoothie (banana, protein powder, milk)', 400, 'mL', 310, 30, 35, 5, ARRAY['general','high-protein','energy-dense','balanced']::text[], NULL, false),
('Turkey Wrap (whole wheat)', 200, 'g', 290, 25, 30, 8, ARRAY['general','high-protein','balanced']::text[], NULL, false),
('Chicken Stir-Fry with Vegetables', 300, 'g', 280, 28, 18, 10, ARRAY['general','high-protein','balanced','low-gi']::text[], NULL, false),
('Grilled Chicken Salad', 300, 'g', 250, 25, 10, 12, ARRAY['general','high-protein','low-calorie','balanced','mediterranean','low-gi','diabetic-friendly']::text[], NULL, false),
('Hummus', 60, 'g', 105, 4, 9, 6, ARRAY['general','mediterranean','low-gi','low-sodium']::text[], NULL, false),
('Salmon with Quinoa and Vegetables', 350, 'g', 370, 32, 28, 14, ARRAY['general','high-protein','balanced','mediterranean','anti-inflammatory']::text[], NULL, false),
('Overnight Oats (with yogurt and berries)', 300, 'g', 280, 12, 40, 8, ARRAY['general','balanced','low-gi','prenatal']::text[], NULL, false),
('Tuna Salad', 150, 'g', 200, 22, 5, 10, ARRAY['general','high-protein','balanced','mediterranean']::text[], NULL, false),
('Vegetable Soup', 250, 'mL', 95, 4, 15, 2, ARRAY['general','low-calorie','low-gi','diabetic-friendly','low-sodium','anti-inflammatory']::text[], NULL, false),
('Lentil Soup', 250, 'mL', 145, 9, 20, 3, ARRAY['general','iron-rich','folate-rich','low-gi','diabetic-friendly','low-sodium']::text[], NULL, false),
('Bean Burrito Bowl (rice, beans, vegetables)', 350, 'g', 340, 18, 45, 10, ARRAY['general','high-carb','balanced','iron-rich']::text[], NULL, false),
('Caprese Salad', 200, 'g', 190, 10, 5, 14, ARRAY['general','mediterranean','low-gi','low-sodium']::text[], NULL, false),
('Egg and Avocado Toast (whole wheat)', 180, 'g', 270, 12, 20, 16, ARRAY['general','balanced','energy-dense','prenatal']::text[], NULL, false),
('Turmeric Golden Milk', 250, 'mL', 130, 6, 15, 5, ARRAY['general','anti-inflammatory','low-gi']::text[], 'Anti-inflammatory spiced milk beverage', false),
('Sardines (canned in olive oil)', 100, 'g', 190, 23, 0, 11, ARRAY['general','high-protein','iron-rich','mediterranean','anti-inflammatory','energy-dense']::text[], 'Rich in omega-3 and calcium', false),
('Rice Cake (plain)', 10, 'g', 37, 1, 8, 0.3, ARRAY['general','low-calorie','low-fodmap','low-sodium']::text[], NULL, false),
('Dark Chocolate (70% cacao)', 30, 'g', 140, 2, 10, 10, ARRAY['general','energy-dense','iron-rich','anti-inflammatory']::text[], NULL, false),
('Coconut Oil', 15, 'mL', 126, 0, 0, 14, ARRAY['general','energy-dense','low-fodmap','low-sodium']::text[], NULL, false),
('Fortified Breakfast Cereal', 30, 'g', 120, 3, 24, 1, ARRAY['general','high-carb','iron-rich','folate-rich','prenatal']::text[], NULL, false),
('Soy Milk (unsweetened)', 250, 'mL', 80, 7, 4, 4, ARRAY['general','high-protein','low-gi','diabetic-friendly','anti-inflammatory','low-sodium']::text[], NULL, false),
('Almond Milk (unsweetened)', 250, 'mL', 35, 1, 1, 3, ARRAY['general','low-calorie','low-gi','diabetic-friendly','low-fodmap','low-sodium']::text[], NULL, false),
('Dried Apricots', 30, 'g', 72, 1, 17, 0.2, ARRAY['general','high-carb','iron-rich','prenatal']::text[], NULL, false),
('Hemp Hearts', 30, 'g', 180, 10, 2, 15, ARRAY['general','energy-dense','high-protein','anti-inflammatory','iron-rich','low-gi','low-sodium']::text[], NULL, false),
('Chicken Thigh (baked, skinless)', 120, 'g', 180, 22, 0, 10, ARRAY['general','high-protein','iron-rich','low-fodmap']::text[], NULL, false),
('Basmati Rice (cooked)', 100, 'g', 116, 3, 25, 0.3, ARRAY['general','high-carb','low-gi','low-fodmap','low-sodium']::text[], NULL, false),
('Mixed Green Salad (no dressing)', 100, 'g', 25, 2, 4, 0.3, ARRAY['general','low-calorie','low-gi','diabetic-friendly','low-sodium','low-fodmap','mediterranean']::text[], NULL, false),
('Balsamic Vinaigrette', 15, 'mL', 55, 0, 3, 5, ARRAY['general','mediterranean','low-fodmap']::text[], NULL, false),
('Ground Turkey (93% lean)', 150, 'g', 180, 27, 0, 8, ARRAY['general','high-protein','balanced','low-fodmap']::text[], NULL, false);
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DELETE FROM ""Foods"" WHERE ""Name"" IN (
'Chicken Breast (grilled)',
'Salmon Fillet (baked)',
'Ground Beef (90% lean)',
'Turkey Breast (roasted)',
'Cod Fillet (baked)',
'Shrimp (cooked, peeled)',
'Eggs (2 large, scrambled)',
'Egg Whites (3 large)',
'Tofu (firm)',
'Tempeh',
'Pork Tenderloin (roasted)',
'Canned Tuna (in water)',
'Lentils (cooked)',
'Chickpeas (cooked)',
'Black Beans (cooked)',
'Edamame (shelled)',
'Rolled Oats (dry)',
'Oatmeal (cooked)',
'Brown Rice (cooked)',
'White Rice (cooked)',
'Quinoa (cooked)',
'Whole Wheat Pasta (cooked)',
'Pasta (cooked)',
'Whole Wheat Bread (1 slice)',
'Sweet Potato (baked)',
'Potato (baked, with skin)',
'Corn Tortilla (1 small)',
'Couscous (cooked)',
'Greek Yogurt (plain, 2%)',
'Cottage Cheese (2%)',
'Whole Milk',
'Skim Milk',
'Cheddar Cheese',
'Mozzarella (part-skim)',
'Parmesan Cheese (grated)',
'Plain Yogurt (whole)',
'Broccoli (steamed)',
'Spinach (raw)',
'Kale (raw, chopped)',
'Zucchini (cooked)',
'Bell Pepper (raw)',
'Carrots (raw)',
'Tomato (raw, medium)',
'Cucumber (raw)',
'Asparagus (steamed)',
'Cauliflower (steamed)',
'Green Beans (steamed)',
'Brussels Sprouts (roasted)',
'Banana (medium)',
'Blueberries',
'Strawberries',
'Mixed Berries',
'Apple (medium, with skin)',
'Orange (medium)',
'Grapes (seedless)',
'Mango (sliced)',
'Olive Oil (extra virgin)',
'Avocado (half)',
'Almonds (raw)',
'Walnuts (raw)',
'Peanut Butter (natural)',
'Chia Seeds',
'Flaxseeds (ground)',
'Pumpkin Seeds (raw)',
'Cashews (raw)',
'Tahini',
'Protein Smoothie (banana, protein powder, milk)',
'Turkey Wrap (whole wheat)',
'Chicken Stir-Fry with Vegetables',
'Grilled Chicken Salad',
'Hummus',
'Salmon with Quinoa and Vegetables',
'Overnight Oats (with yogurt and berries)',
'Tuna Salad',
'Vegetable Soup',
'Lentil Soup',
'Bean Burrito Bowl (rice, beans, vegetables)',
'Caprese Salad',
'Egg and Avocado Toast (whole wheat)',
'Turmeric Golden Milk',
'Sardines (canned in olive oil)',
'Rice Cake (plain)',
'Dark Chocolate (70% cacao)',
'Coconut Oil',
'Fortified Breakfast Cereal',
'Soy Milk (unsweetened)',
'Almond Milk (unsweetened)',
'Dried Apricots',
'Hemp Hearts',
'Chicken Thigh (baked, skinless)',
'Basmati Rice (cooked)',
'Mixed Green Salad (no dressing)',
'Balsamic Vinaigrette',
'Ground Turkey (93% lean)'
);
");
        }
    }
}
